# Generated by Django 5.2.3 on 2025-06-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudantes',
            new_name='Estudante',
        ),
    ]
